name: NPM Test, coverage and lint

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - develop

jobs:
  npm-test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ github.event.pull_request }}"
